"""Books shown on /reading/ as section -> [(title, author)].

Sections are by subject, never by author.
"""

READING = {
    "economics & markets": [
        ("Basic Economics", "Thomas Sowell"),
        ("Applied Economics", "Thomas Sowell"),
        ("Knowledge and Decisions", "Thomas Sowell"),
        ("The Vision of the Anointed", "Thomas Sowell"),
        ("Economic Facts and Fallacies", "Thomas Sowell"),
        ("Wealth, Poverty and Politics", "Thomas Sowell"),
        ("Discrimination and Disparities", "Thomas Sowell"),
        ("Black Rednecks and White Liberals", "Thomas Sowell"),
        ("Intellectuals and Race", "Thomas Sowell"),
        ("The Housing Boom and Bust", "Thomas Sowell"),
        ("Social Justice Fallacies", "Thomas Sowell"),
        ("Charter Schools and Their Enemies", "Thomas Sowell"),
        ("The Road to Serfdom", "F. A. Hayek"),
        ("Free to Choose", "Milton & Rose Friedman"),
        ("Capitalism and Freedom", "Milton Friedman"),
        ("On Liberty", "John Stuart Mill"),
        ("The Theory of Moral Sentiments", "Adam Smith"),
        ("Capitalism in America", "Alan Greenspan & Adrian Wooldridge"),
        ("The Intelligent Investor", "Benjamin Graham"),
        ("The Bogleheads' Guide to Investing", "Larimore, Lindauer & LeBoeuf"),
        ("Liar's Poker", "Michael Lewis"),
        ("Zero to One", "Peter Thiel"),
        ("Read Write Own", "Chris Dixon"),
        ("The Deep Learning Revolution", "Terrence Sejnowski"),
    ],
    "how people decide": [
        ("Thinking, Fast and Slow", "Daniel Kahneman"),
        ("Nudge", "Richard Thaler & Cass Sunstein"),
        ("Behavioral Economics", "Edward Cartwright"),
        ("Freakonomics", "Steven Levitt & Stephen Dubner"),
        ("SuperFreakonomics", "Steven Levitt & Stephen Dubner"),
        ("Fooled by Randomness", "Nassim Nicholas Taleb"),
        ("The Black Swan", "Nassim Nicholas Taleb"),
        ("Skin in the Game", "Nassim Nicholas Taleb"),
        ("Thinking in Bets", "Annie Duke"),
        ("Hidden Potential", "Adam Grant"),
        ("Outliers", "Malcolm Gladwell"),
        ("The Tipping Point", "Malcolm Gladwell"),
        ("David and Goliath", "Malcolm Gladwell"),
        ("What the Dog Saw", "Malcolm Gladwell"),
        ("Talking to Strangers", "Malcolm Gladwell"),
    ],
    "science & ideas": [
        ("The Beginning of Infinity", "David Deutsch"),
        ("All Life Is Problem Solving", "Karl Popper"),
        ("Gödel, Escher, Bach", "Douglas Hofstadter"),
        ("Behave", "Robert M. Sapolsky"),
        ("On the Origin of Species", "Charles Darwin"),
        ("The Evolution of Everything", "Matt Ridley"),
        ("A Short History of Nearly Everything", "Bill Bryson"),
        ("The Wisdom of Psychopaths", "Kevin Dutton"),
        ("Enlightenment Now", "Steven Pinker"),
        ("The Better Angels of Our Nature", "Steven Pinker"),
        ("The Blank Slate", "Steven Pinker"),
    ],
    "philosophy": [
        ("Meditations", "Marcus Aurelius"),
        ("The Present Alone Is Our Happiness", "Pierre Hadot"),
        ("Tao Te Ching", "Lao Tzu"),
        ("Man's Search for Meaning", "Viktor Frankl"),
        ("The Book of Life", "J. Krishnamurti"),
        ("The Book", "Alan Watts"),
        ("The Doors of Perception", "Aldous Huxley"),
        ("What We Owe the Future", "William MacAskill"),
        ("Philosophy: Who Needs It", "Ayn Rand"),
        ("Contemporary Debates in Epistemology", "Steup, Turri & Sosa, eds."),
        ("Readings in Ancient Greek Philosophy", "Cohen, Curd & Reeve, eds."),
        ("Modern Philosophy: An Anthology of Primary Sources", "Ariew & Watkins, eds."),
    ],
    "fiction": [
        ("The Luzhin Defense", "Vladimir Nabokov"),
        ("The Sun Also Rises", "Ernest Hemingway"),
        ("For Whom the Bell Tolls", "Ernest Hemingway"),
        ("The Old Man and the Sea", "Ernest Hemingway"),
        ("The Snows of Kilimanjaro and Other Stories", "Ernest Hemingway"),
        ("Atlas Shrugged", "Ayn Rand"),
        ("The Fountainhead", "Ayn Rand"),
        ("We the Living", "Ayn Rand"),
        ("Anthem", "Ayn Rand"),
        ("Brave New World", "Aldous Huxley"),
        ("1984", "George Orwell"),
        ("Fahrenheit 451", "Ray Bradbury"),
        ("The Moon Is a Harsh Mistress", "Robert A. Heinlein"),
        ("Solaris", "Stanisław Lem"),
        ("Catch-22", "Joseph Heller"),
        ("All Quiet on the Western Front", "Erich Maria Remarque"),
        ("Slaughterhouse-Five", "Kurt Vonnegut"),
        ("As I Lay Dying", "William Faulkner"),
        ("The Grapes of Wrath", "John Steinbeck"),
        ("A Prayer for Owen Meany", "John Irving"),
        ("The World According to Garp", "John Irving"),
        ("Based on a True Story", "Norm Macdonald"),
    ],
}
